Description: AWSServiceRoleForEMRCleanup
Resources:

  # -----------------
  # IAM Role - AWSServiceRoleForEMRCleanup
  # -----------------
  ServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AWSServiceRoleForEMRCleanup
      # Trust relationships
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - 'elasticmapreduce.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      # Permissions
      Policies:
        - PolicyName: emr-cleanup
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "ec2:DescribeInstances"
                  - "ec2:DescribeLaunchTemplates"
                 - "ec2:DescribeSpotInstanceRequests"
                 - "ec2:DeleteLaunchTemplate"
                 - "ec2:ModifyInstanceAttribute"
                 - "ec2:TerminateInstances"
                 - "ec2:CancelSpotInstanceRequests"
                 - "ec2:DeleteNetworkInterface"
                 - "ec2:DescribeInstanceAttribute"
                 - "ec2:DescribeVolumeStatus"
                 - "ec2:DescribeVolumes"
                 - "ec2:DetachVolume"
                 - "ec2:DeleteVolume"
                 - "ec2:DescribePlacementGroups"
                 - "ec2:DeletePlacementGroup"
                Resource: "*"